export const emptyTimetable = [
    {
        monday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        tuesday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        wednesday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        thursday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        friday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        saturday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        sunday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
    },
    {
        monday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        tuesday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        wednesday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        thursday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        friday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        saturday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        sunday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
    },
    {
        monday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        tuesday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        wednesday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        thursday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        friday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        saturday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        sunday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
    },
    {
        monday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        tuesday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        wednesday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        thursday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        friday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        saturday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        sunday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
    },
    {
        monday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        tuesday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        wednesday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        thursday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        friday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        saturday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        sunday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
    },
    {
        monday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        tuesday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        wednesday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        thursday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        friday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        saturday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        sunday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
    },
    {
        monday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        tuesday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        wednesday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        thursday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        friday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        saturday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
        sunday: {name: '', isLecture: false, isSeminar: false, place: '', courseId: 0},
    },
]
